### ISSUE TITLE
[WIP] Installation doc improvement suggestions / beginner perspective experience description

### ISSUE THREAD

**Issue by holgerd77** [ethereum/hive#100]
Hi, this is Holger from ``ethereumjs``, I am just doing my first Hive experience
to prepare for maybe help with the ``ethereumjs-vm`` issue here: https://github.com/karalabe/hive/issues/93

I will write up stuff I stumbled over during installation here, maybe you can 
use this to improve docs a bit.

Doing this with the following pre-requisits:

- Little to no ``Go`` experience
- Good ``ethereum/tests`` insight, practical testing experience
- CI experience

Environment:

- MacBook Air, High Sierra 10.13.1
- Docker version 17.03.0-ce, build 60ccb22
- go version go1.10 darwin/amd64

Note: will live-update 🎥  this during the next two hours and then remove the ``WIP`` label in the title. If you read-up to the last line and have a suggestion during this, feel free to drop a note! 😄 

---

Stumbled over following things:

### Installation

1) Didn't know what to make with the "Note" addition from the install section https://github.com/karalabe/hive#installing-the-hive-validator and how it plays together with the ``go get`` install command from above. Do I have to run the command AND install from Git? Does the command installs somewhere and I have to go there?

2) Ended up using the command (producing absolutely no output, which irritated me a bit) AND doing a ``git clone``.

### Validation

2) Then I went into the repo and tried the ``hive`` command. Failed with "Command not found". Investigating. A note here would be nice.

3) Tried with ``go hive.go ...`` (first guess :-)), didn't work either.

4) Figured out 3), had a look at my ``GOPATH`` with ``go env`` and found the ``bin/hive`` script.

5) Tried again, run into:

```shell
CRIT[03-12|14:01:47] failed to retrieve docker version        error="cannot connect to Docker endpoint"
```

A note that docker has to be up-and-running and in which version would be helpful.

6) Running again, getting...

```
INFO[03-12|13:09:42] building new docker image                client=go-ethereum:master nocache=false
EROR[03-12|13:09:57] failed to build docker image             client=go-ethereum:master error="error creating aufs mount to /var/lib/docker/aufs/mnt/2c62f45e9b58ecaad23ab6cf7128ad8f6eb7786574732f62a4bb4fb66102b625-init: function not implemented"
CRIT[03-12|13:09:57] failed to retrieve client versions       error="clients/go-ethereum:master: error creating aufs mount to /var/lib/docker/aufs/mnt/2c62f45e9b58ecaad23ab6cf7128ad8f6eb7786574732f62a4bb4fb66102b625-init: function not implemented"
```

7) Running again, testing another client ``ethereumj:develop``, getting:

```
INFO[03-12|13:14:27] building new docker image                client=ethereumj:develop nocache=false
EROR[03-12|13:16:16] failed to build docker image             client=ethereumj:develop error="failed to register layer: Error processing tar file(exit status 1): link /usr/share/terminfo/L/LFT-PC850 /usr/share/terminfo/l/lft-pc850: no such file or directory"
CRIT[03-12|13:16:16] failed to retrieve client versions       error="clients/ethereumj:develop: failed to register layer: Error processing tar file(exit status 1): link /usr/share/terminfo/L/LFT-PC850 /usr/share/terminfo/l/lft-pc850: no such file or directory"
```

8) Running ``go-ethereum:stable`` produced the same error as in 6).

9) Updated docker to ``Docker version 17.12.0-ce, build c97c6d6``, still failing.

10) Tried [this](https://github.com/docker/for-mac/issues/1594#issuecomment-299698273) mac specific fix, not working.

11) Tried [this](https://stackoverflow.com/a/35630425) generic fix, at least a new error:

```
INFO[03-12|13:59:42] building new docker image                client=go-ethereum:master nocache=false
EROR[03-12|13:59:42] failed to build docker image             client=go-ethereum:master error="open /var/lib/docker/aufs/layers/c0a2d5e1b904067dd4c3ea2f052c2ea3bffd58ef5a6b6a9940f8d6ad471bf72d: no such file or directory"
CRIT[03-12|13:59:42] failed to retrieve client versions       error="clients/go-ethereum:master: open /var/lib/docker/aufs/layers/c0a2d5e1b904067dd4c3ea2f052c2ea3bffd58ef5a6b6a9940f8d6ad471bf72d: no such file or directory"
```

3h. Will give up for now. Any suggestions welcome!

**Comment by cdetrio** [comment]
Try running with `--loglevel 6` to get [more log output](https://github.com/karalabe/hive/blob/7a372a5d2b6ae74d126ca0f72f82d8625d7cf8a0/images.go#L165-L167).

**Comment by jwasinger** [comment]
@holgerd77 this worked for me: `hive --client='go-ethereum:master' --sim=ethereum/consensus --test=NONE`

**Comment by holgerd77** [comment]
@jwasinger Thanks for letting me know. Not sure when I can re-take on this one though.
