### ISSUE TITLE
discv5 tests currently fail

### ISSUE THREAD

**Issue by Rjected** [ethereum/hive#1073]
Discv5 is not actually enabled in any of the clients for discv5 test suites, and there is no way for the tests to tell `client.sh` files that discv5 should be enabled. As a result, discv5 tests currently fail

**Comment by fjl** [comment]
I'm aware of this. I just added the integration because the tests are implemented in go-ethereum's cmd/devp2p. We can enable them though.

**Comment by fjl** [comment]
Making this work should just be a matter of enabling discv5 on port 30303 alongside discv4.
