### ISSUE TITLE
Issue when trying to deploy callrevert bytecode on hedera

### ISSUE THREAD

**Issue by konstantinabl** [ethereum/hive#1144]
I am trying to build some tests for the rpc relay of the Hedera network, based on [these](https://github.com/ethereum/execution-apis/tree/main/tests) and I need the contracts from the hive repo - https://github.com/ethereum/hive/blob/master/cmd/hivechain/bytecode/callrevert.bin
However, when I try to use the bytecode and deploy those on Hedera I get some errors, which are hard to debug, since I only have the assembly code of the contracts. Do you have a solidity version of the contracts that you may upload for easier debugging?

**Comment by fjl** [comment]
The contracts are written in assembly, there is no Solidity version. You can find the source code here: https://github.com/ethereum/hive/tree/master/cmd/hivechain/contracts
