### ISSUE TITLE
Multistage docker build does not reload base image

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#129]
aleth seems to only ever run on `40566e5` : http://hivetests.ethstats.net/. Seems there's some problem with caching in hive, where it doesn't refetch the base image when building

https://github.com/karalabe/hive/blob/master/clients/aleth:nightly/Dockerfile#L10

cc @chfast

**Comment by chfast** [comment]
We had issue with docker build. Fixed yesterday. New nightly is available.

**Comment by holiman** [comment]
Now it seems stuck on `030ad9c` :  `https://github.com/ethereum/aleth/commit/030ad9ca2e5b41043554096af7a10216a9fb2fe9`

**Comment by chfast** [comment]
I'm not sure if this information helps, but docker does not download images if it already has this tag. This is problematic for tags like `:latest` or `:nightly`.

**Comment by chfast** [comment]
I checked the docker docs.
The `docker pull` will redownload the image tag if it is different.
The `docker build` will not pull the base images if it is available locally. But I have force it by adding `--pull` option.

**Comment by holiman** [comment]
Ok. Added a manual `docker pull ethereum/aleth:nightly` into the script runner now, which hopefully fixes it.

**Comment by chfast** [comment]
You should also add it for `ethereum/aleth:latest`. That's way I suggested add `--pull` flag to `docker build` instead.

**Comment by holiman** [comment]
The image we're using is based on `nightly`: https://github.com/ethereum/hive/blob/master/clients/aleth_nightly/Dockerfile#L10. Also, we don't' do a real `docker build`, that's something hive does internally from somewhere within the go codebase, but I hope that refreshing it from externally should solve the problem.

**Comment by chfast** [comment]
There is also "master": https://github.com/ethereum/hive/blob/master/clients/aleth_master/Dockerfile#L10

**Comment by FrankSzendzielarz** [comment]
@holiman Docker base images need to be pulled explicitly. Do you want me to see if this can be done from within Hive or shall I close the issue?

**Comment by holiman** [comment]
Well... we don't _have to_ fix it, since I have a bypass that works for me... However, if we don't fix it, then we should leave the ticket open. Which is fine by me.

**Comment by fjl** [comment]
We now have the `--docker.pull` option to do this.
