### ISSUE TITLE
Standardise validator output format

### ISSUE THREAD

**Issue by fjl** [ethereum/hive#132]
Validators tend to perform multiple tests in a single run. For example, the consensus validator executes all consensus tests and the rpc-compat validator checks multiple endpoints. Both validators produce a result table. 

It would be nice to have a generic version of that. Running any validator should produce a report that 
visualizes sub-test results across different clients.

One approach would be to output [TAP](https://testanything.org/) from validators and process that in hive. A Go consumer library for TAP [exists](https://github.com/beatgammit/stein) and could be integrated into hive.

**Comment by holiman** [comment]
This is now fixed by @FrankSzendzielarz
