### ISSUE TITLE
Add support for multi-client simulations

### ISSUE THREAD

**Issue by fjl** [ethereum/hive#135]
To test inter-client networking we want to have simulations where different client implementations run against each other. The simulation API doesn't support this at the moment. Here's how to add this feature:

The simulation needs an additional endpoint `/clients` that returns a list of client names as json, i.e.

```
GET /clients

["go-ethereum_stable", "go-ethereum_master", "parity_beta", ...]
```

The request to start a node should include the client name in the request body. We might also want to add support for other parameters such as the bootstrap node.

**Comment by FrankSzendzielarz** [comment]
This was implemented.
