### ISSUE TITLE
Dashboard: links to logs wrong if multiple reports loaded

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#170]
If you load multiple reports and filter for something, e.g. 'RawBalanceGas_d0g0v0_Byzantium', like the picture below: 
![hive](https://user-images.githubusercontent.com/142290/50728762-842a2380-112f-11e9-8792-2db98de74faa.png)

Then one of the two links for `Log` will be wrong. In the example, one is  
`javascript:displayLog('20190104192947/simulator_ethereum_consensus2/parity_master/client-e64195e3.log')`
and the other is
`javascript:displayLog('20190104192947/simulator_ethereum_consensus2/parity_master/client-75bd1b61.log')`

For some reason, when the second report was loaded, the date `20190104192947` somehow seems to have leaked into a global scope, and the base URL is thus wrong. 
The correct URL is obtained when only one report is loaded:
`javascript:displayLog('20190103193957/simulator_ethereum_consensus2/parity_master/client-e64195e3.log')`

**Comment by FrankSzendzielarz** [comment]
Closed by earlier pr
