### ISSUE TITLE
Hive broken if not using `docker-noshell`

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#171]
If executed without `docker-noshell`, the outer image fails to build due to the addition of the `chaintools`, which depend on `go-ethereum`, which has not been vendored in. Cause: https://github.com/ethereum/hive/pull/161

**Comment by FrankSzendzielarz** [comment]
I have pushed a change which should fix this error but not for Windows. I was unable to get this running using DinD on Windows. I don't know if the same difficulties will present themselves on OsX. 
@meowsbits Pls can you check this is now OK for you?

**Comment by meowsbits** [comment]
Thanks @FrankSzendzielarz . My Mac is in the shop currently, but will try when I get it back (probably next week :(.

**Comment by meowsbits** [comment]
If it's not expected that this is fixed for Windows, maybe we should simply open a new issue tracking this bug with that proviso?

**Comment by cdetrio** [comment]
`--docker-noshell` has been the only working mode for as long as I can remember:   https://github.com/ethereum/hive/issues/30

**Comment by FrankSzendzielarz** [comment]
I will try and revisit this at some point. I spent several hours on it yesterday and decided to give it a rest. @meowsbits Good idea, adding a new issue.

**Comment by meowsbits** [comment]
Maybe also/alternatively considering swapping `--docker-noshell` for `--docker-withshell` since it seems the latter is the practical and conventional default. ?

**Comment by FrankSzendzielarz** [comment]
Yes not a bad idea. And it could check the host OS for compatibility. I will add that as an issue too and run it by the others. It's a nice idea, but it means changing the consensus test scripts. On the other hand I am almost done with a fix for running arbitrary client branches which is kind of breaking.
