### ISSUE TITLE
--client='parity.*stable' : Failed to identify the stable branch.

### ISSUE THREAD

**Issue by adilimroz** [ethereum/hive#189]
Ran the following command
`~/go/bin/hive --docker-noshell --client='parity.*stable' --smoke --loglevel=6`

Got following error. Doesn't happen with master and beta (It identifies the respective branches.)

INFO[03-07|15:14:21] docker daemon online                     version=18.09.1
INFO[03-07|15:14:21] building clients for validation          pattern=parity.*stable
INFO[03-07|15:14:21] building validators for testing          pattern=smoke
INFO[03-07|15:14:21] building new docker image                validator=smoke/genesis-chain nocache=false
Step 1/7 : FROM alpine:latest
 ---> caf27325b298
Step 2/7 : RUN apk add --update curl
 ---> Using cache
 ---> 4596de16a792
Step 3/7 : ADD genesis.json /genesis.json
 ---> Using cache
 ---> 8f8a0a1fc6c3
Step 4/7 : ADD chain.rlp /chain.rlp
 ---> Using cache
 ---> 16123b29107b
Step 5/7 : ADD test.sh /test.sh
 ---> Using cache
 ---> 199434a32faf
Step 6/7 : RUN chmod +x /test.sh
 ---> Using cache
 ---> ff19558bc567
Step 7/7 : ENTRYPOINT ["/test.sh"]
 ---> Using cache
 ---> 695474bb8848
Successfully built 695474bb8848
Successfully tagged hive/validators/smoke/genesis-chain:latest
INFO[03-07|15:14:21] building new docker image                validator=smoke/genesis-chain-blocks nocache=false
Step 1/8 : FROM alpine:latest
 ---> caf27325b298
Step 2/8 : RUN apk add --update curl
 ---> Using cache
 ---> 4596de16a792
Step 3/8 : ADD genesis.json /genesis.json
 ---> Using cache
 ---> 8f8a0a1fc6c3
Step 4/8 : ADD chain.rlp /chain.rlp
 ---> Using cache
 ---> 16123b29107b
Step 5/8 : ADD blocks.tar.xz /blocks
 ---> Using cache
 ---> 330547de1c08
Step 6/8 : ADD test.sh /test.sh
 ---> Using cache
 ---> 58ccdc978fee
Step 7/8 : RUN chmod +x /test.sh
 ---> Using cache
 ---> acf05393adb8
Step 8/8 : ENTRYPOINT ["/test.sh"]
 ---> Using cache
 ---> b61db85c080b
Successfully built b61db85c080b
Successfully tagged hive/validators/smoke/genesis-chain-blocks:latest
INFO[03-07|15:14:21] building new docker image                validator=smoke/genesis-keys nocache=false
Step 1/7 : FROM alpine:latest
 ---> caf27325b298
Step 2/7 : RUN apk add --update curl
 ---> Using cache
 ---> 4596de16a792
Step 3/7 : ADD genesis.json /genesis.json
 ---> Using cache
 ---> 8f8a0a1fc6c3
Step 4/7 : ADD keys.tar.xz /keys
 ---> Using cache
 ---> 63468f367585
Step 5/7 : ADD test.sh /test.sh
 ---> Using cache
 ---> 2c6df507c7f1
Step 6/7 : RUN chmod +x /test.sh
 ---> Using cache
 ---> fbea2b5c9dc0
Step 7/7 : ENTRYPOINT ["/test.sh"]
 ---> Using cache
 ---> 6290d9bd32db
Successfully built 6290d9bd32db
Successfully tagged hive/validators/smoke/genesis-keys:latest
INFO[03-07|15:14:21] building new docker image                validator=smoke/genesis-only nocache=false
Step 1/6 : FROM alpine:latest
 ---> caf27325b298
Step 2/6 : RUN apk add --update curl
 ---> Using cache
 ---> 4596de16a792
Step 3/6 : ADD genesis.json /genesis.json
 ---> Using cache
 ---> 8f8a0a1fc6c3
Step 4/6 : ADD test.sh /test.sh
 ---> Using cache
 ---> cc72cada799b
Step 5/6 : RUN chmod +x /test.sh
 ---> Using cache
 ---> d48f00048140
Step 6/6 : ENTRYPOINT ["/test.sh"]
 ---> Using cache
 ---> 58a7c31f1f26
Successfully built 58a7c31f1f26
Successfully tagged hive/validators/smoke/genesis-only:latest
CRIT[03-07|15:14:21] failed to smoke-validate client images   error="open workspace/logs/20190307151421/validator_smoke_genesis-keys/testInfo.json: no such file or directory"

**Comment by holiman** [comment]
I'm afraid I've never tested with the smoke tests... I only run the simulator consensus2

**Comment by FrankSzendzielarz** [comment]
@adilimroz @meowsbits I am switching off other tasks to focus on Hive. During tomorrow I will be merging some other stuff and doing testing. I will bundle the latest issues into this chunk of work. Feel free to add any other requirements right now. I guess I will be on this till end of week.

**Comment by meowsbits** [comment]
Roger, thanks for the heads up :+1:

**Comment by FrankSzendzielarz** [comment]
So this is down to the fact that every 'client' has its own folder in the clients directory in Hive. Parity_Master has a different dockerfile and entry script than say Parity_Beta, and Parity_Stable does not even exist. I propose solving this by removing the regex pattern matching for --client and making the branch separated by a token, eg --client parity::master, parity::beta, parity::stable in an explicit list. The branch would then be passed into the dockerfile as a build-time parameter , if possible.

**Comment by adilimroz** [comment]
@FrankSzendzielarz  Apologies, have been on a vacation so couldn't follow up this thread .

**Comment by FrankSzendzielarz** [comment]
This should be implemented now. Previously Hive demanded that you make a new dockerfile and folder per branch. From now on the client you want under the _clients_ folder is a 'root' client (eg: parity) and the --client option allows you to specify the branch like this  parity_beta, parity_master etc....
