### ISSUE TITLE
Hive installation fails

### ISSUE THREAD

**Issue by adilimroz** [ethereum/hive#190]
cc @FrankSzendzielarz 

While installing the latest hive with 

`go get -v github.com/ethereum/hive
`

It throws an error `undefined: ethdb.NewMemDatabase` and doesn't generate the hive binary.

github.com/ethereum/hive (download)
created GOPATH=/home/adil/go; see 'go help gopath'
github.com/ethereum/go-ethereum (download)
github.com/ethereum/hive/chaintools
#github.com/ethereum/hive/chaintools
go/src/github.com/ethereum/hive/chaintools/chaintools.go:160:8: undefined: ethdb.NewMemDatabase

**Comment by FrankSzendzielarz** [comment]
Should be fixed.
