### ISSUE TITLE
Hive --docker-noshell option not working on Windows.

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#194]
This always terminates with the error that the unix:///var/run/docker.sock docker API endpoint couldn't be reached. 

At first I thought the issue was that on Windows the  "--docker-endpoint tcp://localhost:2375" option was not being passed through to Hive in the shell docker container. That turned out to be incorrect because all the command line arguments are being passed through to the Hive instance in the shell.

Then I realized that the error messages were occurring before the nested Hive program was even being launched, and on closer inspection it seems the Docker-in-Docker image was trying to contact the API and that was where the default unix endpoint was being contacted.

I tried various options to pass the tcp://localhost:2375 endpoint into DinD, basically stabbing in the dark a bit. I was unable to get past this error message (that the unix endpoint couldn't be reached)

**Comment by fjl** [comment]
I think I would rather just remove support for running Hive on Windows. It doesn't work on macOS either, and getting a Linux VM up is really easy.
