### ISSUE TITLE
Get all the new tests running in production regularly

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#196]
Need to make a list of command line calls for Martin to deploy. Also add them to the readme.md as examples.

**Comment by FrankSzendzielarz** [comment]
@holiman I added the command lines for the sync and devp2p tests to the readme.md Pls could you add them to the production run at some point?

**Comment by holiman** [comment]
This is done, right? I'm waiting for you to tell me to deploy all the new candy :)
