### ISSUE TITLE
Add a suite of smoke tests that test Hive itself

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#197]
Recently a number of times, certain test types have regressed because of modifications to the sim api. 

Also, Hive is dependent on geth now.

Some simple tests of each type can be added that don't take too long to run but fully cover the expected Hive functionality. These can be run as part of a periodic Hive build.

**Comment by holiman** [comment]
I agree.. So I guess the best way would be to add a CI integration on the hive repo ? And have a simulator switch that informs the sim the it should be run in 'smoketest' mode, and not do the full test

**Comment by fjl** [comment]
The hive repo now has Circle CI running the smoke tests and Go unit tests.
