### ISSUE TITLE
Remove "[Warning] One or more build-args [branch] were not consumed" warning.

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#199]
The warning crops up and is distracting when doing diagnoses. 

This is basically because the buildImage function in images.go always passes the 'branch' build arg, even if branch is unspecified or irrelevant. Docker warns that it received a build arg but didn't use it. 

Remove this warning by simply not passing the buildArg if the specified branch is empty.

**Comment by fjl** [comment]
Fixed in #343
