### ISSUE TITLE
hive doesn't find docker0 network adapter (failed to lookup bridge IP)

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#200]
Reports of failures that Hive cannot find the bridge IP when running within a GitLab Runner Linux run. 
![issue](https://user-images.githubusercontent.com/33515470/55625800-17fca180-57aa-11e9-9842-7ee41f7e7858.JPG)

**Comment by adilimroz** [comment]
Attaching the complete [log](https://pastebin.com/kYf2seww) . Just in case.

**Comment by fjl** [comment]
This was solved somewhat comprehensively by #599. We no longer need to access the default docker bridge at all.
