### ISSUE TITLE
Add comprehensive RPC API test suite

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#230]
Check if this is still valid https://github.com/ethereum/hive/issues/119

**Comment by tkstanczak** [comment]
@holiman @fjl will this be added? I would like to talk you about it. I was asked by EF to help arrange the JSON RPC standardization (many have failed before) and from my initial conversations it seems that the test suite will be a hugely important item here.

**Comment by fjl** [comment]
We wanted it very much, been wanting it forever.

**Comment by fjl** [comment]
I'm working on fixing the existing RPC test suite right now.

**Comment by tkstanczak** [comment]
@matilote can you check with Felix if you could get this integrated with Nethermind / help with this
@fjl -> I was talking to @matilote and he wanted to work on running this for Nethermind

**Comment by fjl** [comment]
The 'running' part is basically taken care of by Hive, the work here is mostly fixing up the [RPC simulation](https://github.com/ethereum/hive/tree/master/simulators/ethereum/rpc/eth) to work with the newer Hive simulation API. Quite a few things were broken in the last round of heavy Hive development, I'm basically trying to get it back together right now.

It would be very nice to also fix the [other RPC test suite](https://github.com/ethereum/hive/tree/master/simulators/ethereum/rpc-compat). This one is written in python and was also broken by the Hive API changes made during the big refactoring last year. I don't have time to fix that one though. If @matilote is willing and able, he could pick up that one or rewrite it.

**Comment by fjl** [comment]
A warning though: at this time, Hive is still a bit of a mess. It really takes time to figure out how it works, and most documentation is outdated. That's not to say it's impossible to work on, and we would really appreciate help, just need to coordinate.

**Comment by fjl** [comment]
The 'ethclient' RPC simulation now works again. We could still add some more tests to it, but the hard part is done.
The tests found two issues in Nethermind:

- Transaction r, s values are encoded as DATA, not QUANTITY: https://github.com/NethermindEth/nethermind/issues/2372
- `eth_subscribe` is not supported: https://github.com/NethermindEth/nethermind/issues/1405
