### ISSUE TITLE
Simplify how the clients are configured

### ISSUE THREAD

**Issue by FrankSzendzielarz** [ethereum/hive#247]
At the moment, clients are configured using a mix of techniques, such as shell script concatenation of hive environment variables into chainspecs, jq builder and so on.

The recent experiences of integrating nethermind and aleth with the newer tests showed that it's pretty hard to set that configuration up correctly. A much simpler approach would be desirable.

In the upcoming Hive v2 all tests will be 'simulations' controlling the execution of 'TestSuites' through an API, implemented by a provider. Those APIs can be extended to somehow **allow passing  a Hive-common 'config json'**  when requesting a new node from the provider. Each client container folder would then include a standard subfolder, 'config,' which would contain whatever files it required (**chainspec.json, genesis.json etc), but with escaped *symbols* referring to the common config json paths.** During client container instantiation, the symbols would be parsed and overwritten.

eg generic forks section:

```
{
    "Forks":[
    {
        "forkID":"Eth1ForkN",
        "forkLabel":"eg:Constantinople",
        "block":1234,
        "includedEIPs:":["EIP1", "EIP2", "EIPN","Only included for forward compatibility if EIPs become flexible in private networks"] 
    },
    {
        "forkID":"Development",
        "includedEIPs:":["EIP100", "EIP101", "EIP102"]
    }]


}
```

This would make Hive client integration simpler, but more importantly, much easier to understand and maintain. Further, the code could be re-used to offer a local or online service (perhaps driven by UI) for specification of private networks. These config folders could eventually be submitted to the client source repos themselves, perhaps allowing for an Ethereum-wide common config mechanism.

**Comment by fjl** [comment]
The current client launch config system using environment variables is actually good enough for everything and we don't need anything more complicated than this.
