### ISSUE TITLE
Permalink functionality (viewer)

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#284]
Right now, when we load a testsuite, the suite get's "permalinked" by adding it to the location via history api. 
A better solution would be to have a "permalink" button, which would, 
- put the testsuite into the url
- put any datatable filters into the url, 
- put datatable sort-column/order into the url, 

Loading page would then apply those parameters. It would be easy to show someone a specific result. 
Current viewer is here: https://github.com/holiman/testreport_template

**Comment by fjl** [comment]
This is improved in #348. The datatable filters etc. are not tracked, but basic navigation and linking works.

Anything beyond the changes in #348 will be a lot of work and will mess up the app code a lot. I think it would be good to split up the 'tabs' in the UI into individual HTML pages with exactly one purpose per page. It would simplify the app, but I don't want to spend more time on it right now.

**Comment by fjl** [comment]
Linking to tests is now possible. Closing this now because I think it's good enough. 

The situation of wanting to share a specific view of the tests table with search+sort order is pretty rare, and I think it'd be kind of confusing to have a button that creates the link.
