### ISSUE TITLE
Simulation network

### ISSUE THREAD

**Issue by cuita85202** [ethereum/hive#289]
Hey,

Thank you for this very good tool.
I have a question that is not an issue Actually, I'd like to simulate my network performances about how fast they can vote and validate a smart contract. for that I neet to creat a virtual validator (nodes with Oment++ maybe?), and evaluate in the same time how much transaction do they receive every seconde and how much transaction do they reject..?

So my question: if this is a tool that Im looking for to get this simulations done?

**Comment by holiman** [comment]
Hive is not a good tool to simulate real life networking conditions, if that's what you mean. It's more about reliably spin up machines and control how they see the world, which peers they can talk to etc. So I'd advice to look somewhere else
