### ISSUE TITLE
Problem with installing hive validator via GO GET

### ISSUE THREAD

**Issue by SebastianDremo** [ethereum/hive#292]
Trying to install hive with 
```go get github.com/ethereum/hive```
getting error: 
```
# github.com/ethereum/hive/chaintools
../go/src/github.com/ethereum/hive/chaintools/chaintools.go:173:39: not enough arguments in call to core.NewBlockChain
	have (ethdb.Database, nil, *params.ChainConfig, *SealingEthash, vm.Config, nil)
	want (ethdb.Database, *core.CacheConfig, *params.ChainConfig, consensus.Engine, vm.Config, func(*types.Block) bool, *uint64)
```

ENV: 
* go version go1.14.4 linux/amd64
* Ubuntu 18.04 
* GO111MODULE=on

Note to add -> I once had hive installed on machine but had to remove it due to too much changes made and need to start fresh

**Comment by karalabe** [comment]
Are you sure `GO111MODULE=on` is set globally? The error message is because hive internally uses an older version of the `go-ethereum` repo. Go 1.14.4 does **not** enable go modules by default.

E.g.

```
$ cd /tmp
$ export GOPATH=/tmp/go
```

```
$ go get -v github.com/ethereum/hive
[...]
go/src/github.com/ethereum/hive/chaintools/chaintools.go:173:39: not enough arguments in call to core.NewBlockChain
	have (ethdb.Database, nil, *params.ChainConfig, *SealingEthash, vm.Config, nil)
	want (ethdb.Database, *core.CacheConfig, *params.ChainConfig, consensus.Engine, vm.Config, func(*types.Block) bool, *uint64)
```

```
$ GO111MODULE=on go get -v github.com/ethereum/hive
[...]
<done>
$ ls -al ./go/bin/hive
-rwxrwxr-x 1 karalabe karalabe 15449752 Jun 15 16:13 ./go/bin/hive
```

**Comment by SebastianDremo** [comment]
`$ GO111MODULE=on go get -v github.com/ethereum/hive` did the job. 
I guess you were right that `GO111MODULE` wasn't set globally. 
Many thanks :) 

IMO `$ GO111MODULE=on go get -v github.com/ethereum/hive` should be the default way of installing hive instead of `$ go get github.com/ethereum/hive` as README says - for people like me with 0 knowledge about golang
