### ISSUE TITLE
Nethermind problems (part II)

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#308]
A lot of tests fail on nethermind/hive. When they do, this is what's shown:

```

2020-08-10 12:18:45.2143\|HIVE Processing block file: /blocks/0001.rlp - 1 (0x3ef18c...f9d9dc)
--
  | 2020-08-10 12:18:45.2143\|HIVE suggested 1 (0x3ef18c...f9d9dc), now best suggested header Hash: 0xb5bfc99a87a680ef055187b49cf805bd582456532d14ee9f57ef549d29a8554c
  | Number: 0
  | Parent: 0x0000000000000000000000000000000000000000000000000000000000000000
  | Beneficiary: 0x1000000000000000000000000000000000000000
  | Gas Limit: 23826461031063688
  | Gas Used: 0
  | Timestamp: 0
  | Extra Data: 00
  | Difficulty: 131072
  | Mix Hash: 0x0000000000000000000000000000000000000000000000000000000000000000
  | Nonce: 0
  | Ommers Hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347
  | Tx Root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  | Receipts Root: 0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421
  | State Root: 0x1366cee54e767fa0550195b99b72ab3d6f9675ea9a0d1ae65423e3b73bb1a60b
  | , head 0 (0xb5bfc9...a8554c)
  | 2020-08-10 12:18:45.2143\|HIVE initialization completed

```
It can be interpreted as: 

`HIVE suggested 1 (0x3ef18c...f9d9dc`, but ` best suggested` hash is `0xb5bfc99a87a680ef055187b49cf805bd582456532d14ee9f57ef549d29a8554c`, a.k.a `genesis`. Thus, the 'suggested" block was rejected. 

I think it would help a lot of the importer specified _why_ the block was considered 'bad', and thus rejected. Otherwise it's very hard to figure anything out. 

cc @tkstanczak @SebastianDremo

**Comment by holiman** [comment]
Example not imported: https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-151d0ec8.log
Example of failed import: https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-0d2daaab.log

**Comment by tkstanczak** [comment]
I am pretty sure it is because of the magic block reward on Hive. This is scheduled for fix and with Sebastian.

**Comment by holiman** [comment]
cc @SebastianDremo any progress on this?

**Comment by tkstanczak** [comment]
@holiman Sebastian prepared some test for me, genesis is getting rejected with an incorrect genesis hash in most of the cases, did not have time yet to look at this, lower prio as all these tests pass on our CI

**Comment by tkstanczak** [comment]
but we do want to get it sorted as soon as possible
there is something wrong either at chainspec generation level or similar

**Comment by holiman** [comment]
Well, wouldn't just emitting some log message be a good start? I realize it is hard to fix it without knowing what exactly is happening... Would we know more if I increased the node verbosity?

**Comment by fjl** [comment]
I've tried to make the chainspec generator more obvious in #329, but it still produces the same kind of genesis mismatch error.

We also found another issue https://github.com/NethermindEth/nethermind/issues/2332 while trying to do some network tests. This one prevents us from doing any network testing with Nethermind at the moment, and it's also the reason why all the 'sync' tests fail with it.

**Comment by tkstanczak** [comment]
@fjl thanks, confirmed, will see how quickly we can resolve this
@SebastianDremo -> I think this would be great investment of our time to do that before everything else -> Geth test team here saves us a lot of time in the long term by running their tools against Nethermind
(thanks guys!)

**Comment by holiman** [comment]
Now nethermind shows some more logs. See for example: 
https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-91ceb1d2.log#L205

```

  | 2020-10-08 00:35:44.1511\|HIVE Processing block file: /blocks/0001.rlp - 1 (0x4a8d48...2c3bd5)
-- | --
  | WRONG SUGGESTED BLOCK NOT WHAT HIVE SUGGESTED
  | 2020-10-08 00:35:44.1528\|HIVE suggested 1 (0x4a8d48...2c3bd5), now best suggested header Hash: 0xb5bfc99a87a680ef055187b49cf805bd582456532d14ee9f57ef549d29a8554c
  |  

```
So `0xb5b...` is what nethermind sees as the genesis. And the test fails for this reason: 
```
Genesis mismatch, expected 0xb835c89a42605cfcc542381145b83c826caf10823b81af0f45091040a67e6601 got 0xb5bfc99a87a680ef055187b49cf805bd582456532d14ee9f57ef549d29a8554c
```
So we can suppose that the `block 1` references the genesis as `0xb835..`, not `0xb5b...`, which is why it's rejected. So something is still off with the way we create the genesis for Nethermind. And here is what we present to it: https://hivetests.ethdevops.io/viewer.html?file=results/nethermind_latest/client-91ceb1d2.log#L5 .

**Comment by holiman** [comment]
So if @SebastianDremo can feed that spec to a nethermind node, and figure out the exact header fields that go into the rlp preimage for hashing, I can do the same with geth, and we should be able to see what the problem is pretty easily

**Comment by holiman** [comment]
Here is the header rlp which geth sees: `f901f7a00000000000000000000000000000000000000000000000000000000000000000a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347941000000000000000000000000000000000000000a0642a369a4a9dbf57d83ba05413910a5dd2cff93858c68e9e8293a8fffeae8660a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421a056e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000083020000808754a60a4202e088808000a00000000000000000000000000000000000000000000000000000000000000000880000000000000000`, which consists to this rlp structure: 
```
[
  0000000000000000000000000000000000000000000000000000000000000000,
  1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347,
  1000000000000000000000000000000000000000,
  642a369a4a9dbf57d83ba05413910a5dd2cff93858c68e9e8293a8fffeae8660,
  56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
  56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421,
  00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
  020000,
  "",
  54a60a4202e088,
  "",
  "",
  00,
  0000000000000000000000000000000000000000000000000000000000000000,
  0000000000000000,
]
```

**Comment by tkstanczak** [comment]
thanks @holiman , I think we should print out more info for Hive
hope to have a look at this with @SebastianDremo 

I think that currently by passing --log TRACE to Nethermind one could see the entire blocks as they are processed

**Comment by tkstanczak** [comment]
@SebastianDremo this code is not single-threaded:
![image](https://user-images.githubusercontent.com/498913/95431838-c0626780-0945-11eb-8eee-33b017ad7241.png)

after suggesting a block you need to wait for it to be processed as the processor thread is independent from the block tree and has its own processing queues.

**Comment by holiman** [comment]
@tkstanczak regardless though, there's a genesis hash mismatch there, so I'm fairly certain that is the root culprit.

**Comment by holiman** [comment]
> Here is the header rlp 

That ^ was the genesis header, which produced `0xb835c89a42605cfcc542381145b83c826caf10823b81af0f45091040a67e6601`, but which nethermind calculates into something else. I suspect it's most likely the stateroot being different (geth genesis stateroot becomes `1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347`)

**Comment by tkstanczak** [comment]
> > Here is the header rlp
> 
> That ^ was the genesis header, which produced `0xb835c89a42605cfcc542381145b83c826caf10823b81af0f45091040a67e6601`, but which nethermind calculates into something else. I suspect it's most likely the stateroot being different (geth genesis stateroot becomes `1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347`)

there is enough information for us to find out what the problem is - if this is waiting for a resolution it is entirely on us now

**Comment by fjl** [comment]
OK, we figured out something. We were trying to connect with the 'latest' docker tag, but actually you are only updating the 'alpine' tag. We tried with the 'alpine' tag now, but now there is a different issue: the client imports from chain.rlp, and seems to accept the blocks, but the head block is not updated: https://gist.github.com/fjl/823b1579daa7f4a8c8f68263a26a8179

**Comment by fjl** [comment]
It would be nice if you guys could push to the 'latest' docker hub tag instead of 'alpine'. The image is actually based on Ubuntu (not Alpine) and it took us a while to figure out we're using an old image.

**Comment by fjl** [comment]
@SebastianDremo when you fix it, please also flip the loading order around so the /chain.rlp blocks are inserted to completion BEFORE processing individual block files from /blocks.

**Comment by tkstanczak** [comment]
@matilote can you confirm the Alpine tag thing?
@SebastianDremo do you know why it is only Alpine? also let me know if the chain.rlp thing can be fixed (to load BEFORE /blocks)

**Comment by fjl** [comment]
<img width="577" alt="Screenshot 2020-10-19 at 20 53 41" src="https://user-images.githubusercontent.com/6915/96499117-47b8b080-124d-11eb-8bce-b10ad1ad917d.png">
