### ISSUE TITLE
BESU failures

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#314]
All consensus tests fail: 

![Screenshot_2020-08-26 https hivetests ethdevops io](https://user-images.githubusercontent.com/142290/91290024-62156700-e793-11ea-8944-af4d858a2b42.png)

probable cause:
```

  | 2020-08-20 07:51:56.819+00:00 \| vert.x-eventloop-thread-5 \| INFO  \| JsonRpcHttpService \| JSON-RPC service started and listening on 0.0.0.0:8545
-- | --
  | 2020-08-20 07:51:56.820+00:00 \| main \| INFO  \| GraphQLHttpService \| Starting GraphQL HTTP service on 0.0.0.0:8545
  | 2020-08-20 07:51:56.847+00:00 \| main \| INFO  \| Runner \| Ethereum main loop is up.
  | 2020-08-20 07:51:56.852+00:00 \| vert.x-eventloop-thread-6 \| INFO  \| GraphQLHttpService \| GraphQL HTTP service started and listening on 0.0.0.0:8545
  | 2020-08-20 07:51:56.857+00:00 \| main \| INFO  \| AutoTransactionLogBloomCachingService \| Starting auto transaction log bloom caching service.


```
-- it seems besu doesn't handle both graphql and json-rpc on the same port, I suppose graphql takes precendence. 

cc @shemnon , is that correct? If so, I can work around it since consensus tests doesn't need graphql

**Comment by shemnon** [comment]
I would have expected it to fail to start.  Guess not.  Issue here - https://github.com/hyperledger/besu/issues/1340
