### ISSUE TITLE
Invalid json on stdout

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#36]
The output from hive is not 'pure' json, but invalid due to the occurrence of some output. I've no idea where the output comes from, but I'm suspecting the dind-things.

This is my patchy workaround, for now: 
```bash
hive -sim ethereum/consensus -test none -client .*:master\|cpp-ethereum.* 2> output.log > tmp.json

# Remove stuff like the following, which makes it out to stdout:
# ....
# 3adb531f0ab5
# 5350e9a0cce0
# Deleted: sha256:f207844cbb94230c85696310f93a5869a8a89c6eef8a31a83ef744f150d72c0e
#

cat tmp.json                    | \
	grep -v -P "^[\.]+$"        | \
	grep -v -P "^[a-f0-9]{12}$" | \
	grep -v "^Deleted: sha256:"   \
	> data.json


```

**Comment by holiman** [comment]
Hm, it appears the `Deleted: sha256...` and `<hexdigits>` actually comes from Docker. See for example https://github.com/docker/docker/issues/26862 . Would be good to 'squelch' those, if possible.

**Comment by SomniaStellarum** [comment]
As a way to fix this issue, I think you can simply redefine os.Stdout to another file (likely a log file). Then then use the os.Stdout variable (saved to another variable) to only output proper json.

**Comment by holiman** [comment]
This is only a minor nuisance, and I would suspect it's a bit of a timesink. I personally believe the output comes from somewhere internally within docker, and we already have a workaround for it, so it doesn't really seem worth the bother
