### ISSUE TITLE
Failed to start node

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#37]
As can be see here : http://martin.swende.se/foobar/report-2017-02-26_16-18-22/#execfilter=blockhash0_d0g0v1_EIP158 , sometime client-instantiation fails with 
```
Failed to start node (Failed to POST req (500):API error (500): {"message":"device or resource busy"}
``` 

This is probably a 500 error from within Hive. I can try to work around it by retrying from the simulator-side, but maybe it can  be fixed within hive?

**Comment by karalabe** [comment]
This might have been caused by the file descriptors not being closed properly/fast enough. Could you eventually run a new batch with the latest hive code that added the fixes?
