### ISSUE TITLE
Simulator ethereum/engine: Difficulty bomb PoW Merge Tests

### ISSUE THREAD

**Issue by marioevz** [ethereum/hive#508]
There are two potential relevant test cases for the merge transition that have been identified, related to the difficulty bomb hitting mainnet before the merge happens:
### The block that hits the TTD has a _much_ higher difficulty than its parent
This test case would require that the clients somehow accept a block with a significant increase in difficulty.
An initial idea would be to create a fake hard-fork which pushes the difficulty bomb forward, so the bomb goes off immediately on the first blocks from genesis.

### The block that hits the TTD is created much later than its parent
The TTD block takes a couple of minutes to be mined, this test would check that the CL keeps producing slots/blocks without issues in the meantime and that, when the TTD block is finally available, the merge happens, and blocks go back to 12-sec.
An initial idea would be to have a simulator testnet with PoW enabled, and having a separate miner which is capable of recognizing and withholding the TTD-reaching block for a couple of minutes before broadcasting it to clients.

**Comment by fjl** [comment]
We probably won't add those tests since the merge is now over.
