### ISSUE TITLE
Consider a different status for tests that are not executed because we fail to start a client node

### ISSUE THREAD

**Issue by gsalgado** [ethereum/hive#52]
The consensus simulator will [mark a test as failed if it can't start a client node](https://github.com/karalabe/hive/blob/master/simulators/ethereum/consensus/hivemodel.py#L297) to run the test against, but that's not accurate as the test didn't actually run. We could use the skipped status, but that may be confusing as skipped is used for blacklisted tests -- although currently we don't seem to blacklist any consensus tests

I'd be happy to fix the code myself, just wanted to first check if this is desirable and what status to use

**Comment by fjl** [comment]
This is a very old issue, and a lot has changed in Hive, but it still kind-of works the same way. I think the current behavior is OK because the client not starting indicates there is a bug in the client launcher script.
