### ISSUE TITLE
Make Pass/Fail Wording in the WebUI Less Ambiguous

### ISSUE THREAD

**Issue by SeaMonkey82** [ethereum/hive#565]
While it can be easily determined by looking at the results, in the WebUI, there is a column called `Pass` and the results are expressed as `Fail (# / #)` where `(# / 110)` might be misinterpreted as the number of tests that passed.  I suggest the wording of the results be changed to `Failed # / 110 tests`.

**Comment by fjl** [comment]
The column was recently renamed to `Status`. I think that's good enough.
