### ISSUE TITLE
Can't run `hive` on mac os

### ISSUE THREAD

**Issue by lightclient** [ethereum/hive#571]
Because per container ip addressing is [not possible](https://docs.docker.com/desktop/mac/networking/#per-container-ip-addressing-is-not-possible) on mac os, hive cannot connect to client container to [check it is up](https://github.com/ethereum/hive/blob/87f2d1fcd4372c69ec919e5ac0aff29ea59327d7/internal/libdocker/container.go#L173-L190).

**Comment by fjl** [comment]
It works now.
