### ISSUE TITLE
Simulator ethereum/engine: Flaky test: JWT Authentication: Positive time drift, exceeding limit, correct secret

### ISSUE THREAD

**Issue by daniellehrner** [ethereum/hive#602]
The test `JWT Authentication: Positive time drift, exceeding limit, correct secret` seems to be flaky. The `iat` value of this test is supposed to be 6 seconds in the future, but that is not always the case. For example here is an excerpt from the Besu log files:

```
2022-07-12 10:48:21.042+00:00 \| vert.x-eventloop-thread-1 \| TRACE \| EngineAuthService \| Received token: {"accessToken":{"iat":1657622906},"iat":1657622906,"rootClaim":"accessToken"}
```

We are receiving a token with `iat` set to 1657622906 which is equivalent to Jul 12 2022 10:48:26 GMT+0000.  We are receiving this at Jul 12 2022 10:48:21 GMT+0000. Which means the token is still valid, because the `iat` value is only 5 seconds in the future instead of 6. This causes the test to fail from time to time, like it did in the following test run: https://hivetests2.ethdevops.io/?page=v-pills-results-tab&suite=1657673028-d82dc458598ad846fc8bea7d7747072f.json  

I am not sure what is causing this, so unfortunately I cannot suggest a fix. A simple workaround would be to change the test to be 7 seconds in the future instead of 6.

**Comment by jangko** [comment]
I think all test cases in `authtests.go` can be flaky.

They assume `now` in simulator and `now` in EL are equal. But they are not. By the time the request arrived, `now` in EL have been move forward, thus the delta shift is not the same as in the simulator.
