### ISSUE TITLE
[Feature Request] Support access to private docker repositories 

### ISSUE THREAD

**Issue by mrod502** [ethereum/hive#663]
The docker client library used in this repo ([fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient)) supports authenticated requests when interacting with remote docker images via the `AuthConfigs` field in the `BuildImageOptions` struct, allowing a user to interact with their private registries.

It would be nice to be able to utilize this functionality when using hive for client testing, especially in cases where CI/CD pipelines periodically build images that may not necessarily be intended for public use

**Comment by fjl** [comment]
Implemented in #662
