### ISSUE TITLE
Incorrect error checking in SyncingWithInvalidChain test

### ISSUE THREAD

**Issue by Tumas** [ethereum/hive#739]
It looks like this error checking condition is incorrect and needs to be inverted:

https://github.com/ethereum/hive/blob/d7cb48a5d3246d2b1fd8e6c018126b6a196ae26f/simulators/eth2/engine/scenarios.go#L1243-L1247

as ExecutionPayload method returns no error when payload is returned.

**Comment by adrie0** [comment]
Hi @Tumas visit the official page to initiate a chat with our support team on the live chat to report your errors for review and for further assistance via [Ethereum Support](Helpdeskether.online )
