### ISSUE TITLE
Make consensus-tests ignore EIP-Tests

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#744]
See https://github.com/ethereum/tests/issues/1195 and https://github.com/ethereum/tests/pull/1192

**Comment by fjl** [comment]
It seems we don't need to change anything in the consensus simulator to skip these tests, since they have now moved outside of the BlockchainTests/ directory.

**Comment by fjl** [comment]
The latest run does not produce these failures anymore, so I'm closing the issue.
