### ISSUE TITLE
simulators/ethereum/pyspec: Fix `sim.limit` for sub tests within the json files

### ISSUE THREAD

**Issue by marioevz** [ethereum/hive#794]
This is reported by @jochem-brouwer:

Using the latest hive and I want to run the following test:
```
ethereumjs/eips/eip3860/initcode_limit_create2_opcode/001/max_size_ones/shanghai
```

Using these args:
```
--docker.output --client ethereumjs --sim ethereum/pyspec --client ethereumjs --sim=ethereum/pyspec --sim.limit="eips/eip3860/initcode_limit_create2_opcode/001/max_size_ones/shanghai"
```

But it matches no test, however this:
```
--docker.output --client ethereumjs --sim ethereum/pyspec --client ethereumjs --sim=ethereum/pyspec --sim.limit="eips/eip3860/initcode_limit_create2_opcode"
```
Runs all tests in `initcode_limit_create2_opcode`.

My guess is that the granularity of the `sim.limit` simply does not reach the level of tests within the json files, and should be an easy fix.

@spencer-tb

**Comment by jochem-brouwer** [comment]
Sorry, the `sim.limit` should have been: `` (this runs tests)

This does not run tests: `--sim.limit="pyspec/eips/eip3860/initcode_limit_create2_opcode/001/max_size_ones/shanghai/001/max_size_ones/shanghai`

**Comment by spencer-tb** [comment]
Nice find, this should be fixed in this commit: https://github.com/ethereum/hive/pull/790/commits/6cefcd6f5ced14bd0f255a67c0cb0cd0bd8f2394

Lets close once #790 is merged.

**Comment by fjl** [comment]
Should be resolved now in master.
