### ISSUE TITLE
Make hive use IPC connection

### ISSUE THREAD

**Issue by holiman** [ethereum/hive#86]
From what I can tell; https://github.com/karalabe/hive/blob/master/simulator.go#L309 , the simulator uses the `ip:8545` to connect to the client API. This is a bit problematic for cpp: https://github.com/ethereum/cpp-ethereum/pull/4635#issuecomment-351362487 

> We recently removed HTTP server from eth, now instead of `--json-rpc --json-rpc-port 8545 --admin-via-http` you need to run `scripts/jsonrpcproxy.py`

Doing it this way requires us to add python to the alpine image, so it'd be neat to just use the ipc path instead.

**Comment by fjl** [comment]
We cannot do this because some clients don't support IPC. JSON-RPC over HTTP is the lowest common denominator interface.
