### ISSUE TITLE
Support ganache-core (aka RPC methods over ethereumjs-vm)

### ISSUE THREAD

**Issue by axic** [ethereum/hive#93]

**Comment by axic** [comment]
@benjamincburns fancy implementing this? :)

**Comment by benjamincburns** [comment]
Yes. I actually have this on my roadmap already, though it keeps getting pushed out by more sparkley things. Once the current ganache suite beta releases are released as stable I’ll hopefully get a chance to tackle this.

**Comment by axic** [comment]
cc @cdetrio @jwasinger

**Comment by holgerd77** [comment]
@axic Could you provide a more thorough description of what you had in mind and what alternative approach you could imagine? Didn't have any contact with ``Hive`` yet and this could help. Also can't imagine yet what role ``ganache-core`` would take in here.

**Comment by holgerd77** [comment]
@axic addition: please do directly in your first issue opening comment.

**Comment by fjl** [comment]
I think ganache will never be added in hive, since we won't be able to run most tests with it. The only simulator it could potentially work with is rpc-compat, but ganache might as well just import the test vectors from http://github.com/ethereum/execution-apis and run them as unit tests.
