### ISSUE TITLE
simulators/ethereum/engine: `BlockBy*` requests are failing for some clients due to blobs missing `v` field

### ISSUE THREAD

**Issue by marioevz** [ethereum/hive#947]
According to https://ethereum.github.io/execution-apis/api-documentation/, transaction json format that is returned by `eth` endpoints that return blocks must follow the format of `eth_getTransactionByHash`, which, starting on blob transactions, contain only the `yParity` value and not the `v` value.

Currently hive is complaining as follows:
```
Unexpected error on BlockByNumber: missing required field 'v' in transaction
```

This should not be an issue and the test should be looking for `yParity` instead, or, at the very least, accept either field (`v` or `yParity`).

**Comment by marioevz** [comment]
Opened a PR https://github.com/ethereum/go-ethereum/pull/28564 to start addressing this, and once it makes it into master we can update the dependency in the simulator.

**Comment by fjl** [comment]
Should be fixed by now.
